// castramap-angular/src/app/components/ui/breadcrumb/breadcrumb.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AppIconComponent } from '../../app-icon/app-icon.component'; // Adjust path

@Component({
    selector: 'app-breadcrumb',
    standalone: true,
    imports: [CommonModule, RouterModule, AppIconComponent],
    templateUrl: './breadcrumb.component.html',
    styleUrls: ['./breadcrumb.component.css']
})
export class BreadcrumbComponent {
    @Input() items: { label: string, path: string }[] | null = null;

    get breadcrumbItems() {
        return this.items || [{ label: 'Табло', path: '/dashboard-overview' }];
    }
}

<nav aria-label="Breadcrumb" class="breadcrumb-nav">
    <ol class="breadcrumb-list">
        <li *ngFor="let item of breadcrumbItems; let last = last; let i = index" class="breadcrumb-item">
            <ng-container *ngIf="i > 0">
                <app-icon name="ChevronRight" [size]="16" class="separator-icon"></app-icon>
            </ng-container>

            <span *ngIf="last; else link" class="current-page" aria-current="page">
                {{ item.label }}
            </span>

            <ng-template #link>
                <a [routerLink]="item.path" class="breadcrumb-link">
                    {{ item.label }}
                </a>
            </ng-template>
        </li>
    </ol>
</nav>

// src/components/ui/Breadcrumb.jsx
import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import Icon from '../AppIcon';

const Breadcrumb = ({ items }) => {
  const location = useLocation();

  const defaultItems = [
    { label: 'Табло', path: '/dashboard-overview' },
  ];

  const breadcrumbItems = items || defaultItems;

  return (
    <nav aria-label="Breadcrumb" className="py-4">
      <ol className="flex items-center gap-2 text-sm">
        {breadcrumbItems?.map((item, index) => {
          const isLast = index === breadcrumbItems?.length - 1;
          const isActive = location?.pathname === item?.path;

          return (
            <li key={item?.path} className="flex items-center gap-2">
              {index > 0 && (
                <Icon 
                  name="ChevronRight" 
                  size={16} 
                  className="text-muted-foreground" 
                />
              )}
              {isLast || isActive ? (
                <span 
                  className="font-medium text-foreground"
                  aria-current="page"
                >
                  {item?.label}
                </span>
              ) : (
                <Link
                  to={item?.path}
                  className="text-muted-foreground hover:text-foreground transition-smooth"
                >
                  {item?.label}
                </Link>
              )}
            </li>
          );
        })}
      </ol>
    </nav>
  );
};

export default Breadcrumb;
