// castramap-angular/src/app/components/ui/header/header.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router, NavigationEnd } from '@angular/router';
import { ButtonComponent } from '../button/button.component'; // Adjust path
import { AppIconComponent } from '../../app-icon/app-icon.component'; // Adjust path
import { filter } from 'rxjs/operators';

@Component({
    selector: 'app-header',
    standalone: true,
    imports: [CommonModule, RouterModule, ButtonComponent, AppIconComponent],
    templateUrl: './header.component.html',
    styleUrls: ['./header.component.css']
})
export class HeaderComponent {
    isMobileMenuOpen = false;

    navigationItems = [
        { label: 'Табло', path: '/dashboard-overview', icon: 'LayoutDashboard' },
        { label: 'Регистрирани', path: '/cat-registry-list', icon: 'BookOpen' },
        { label: 'Карта', path: '/interactive-cat-map', icon: 'Map' },
    ];

    constructor(private router: Router) {
        // Scroll to top on navigation or logic handling?
        // React had ScrollToTop component. We might need that global logic.
        // For isActivePath, we can use router url or RouterLinkActive in template.
    }

    toggleMobileMenu() {
        this.isMobileMenuOpen = !this.isMobileMenuOpen;
    }

    closeMobileMenu() {
        this.isMobileMenuOpen = false;
    }
}

<header class="header">
    <div class="header-container">
        <div class="flex items-center gap-6">
            <a routerLink="/dashboard-overview" class="logo-link" (click)="closeMobileMenu()">
                <div class="logo-icon-wrapper">
                    <div class="logo-icon-inner">
                        <img src="logo.png" alt="CastraMap logo" class="logo-image" />
                    </div>
                </div>
                <span class="logo-text hidden sm:block">CastraMap</span>
            </a>

            <nav class="desktop-nav hidden lg:flex">
                <a *ngFor="let item of navigationItems" [routerLink]="item.path" routerLinkActive="active"
                    class="nav-item">
                    <app-icon [name]="item.icon" [size]="18"></app-icon>
                    <span>{{ item.label }}</span>
                </a>
            </nav>
        </div>

        <div class="flex items-center gap-3">
            <app-button variant="default" iconName="Plus" iconPosition="left" class="hidden sm:flex"
                routerLink="/cat-registration-form">
                Нова котка
            </app-button>

            <app-button variant="default" size="icon" iconName="Plus" class="sm:hidden"
                routerLink="/cat-registration-form" aria-label="Регистрирай котка"></app-button>

            <button (click)="toggleMobileMenu()" class="mobile-menu-btn lg:hidden" aria-label="Toggle menu"
                [attr.aria-expanded]="isMobileMenuOpen">
                <app-icon [name]="isMobileMenuOpen ? 'X' : 'Menu'" [size]="24"></app-icon>
            </button>
        </div>
    </div>
</header>

<div *ngIf="isMobileMenuOpen" class="mobile-menu-overlay" (click)="closeMobileMenu()">
    <div class="mobile-menu-content" (click)="$event.stopPropagation()">
        <nav class="mobile-nav">
            <a *ngFor="let item of navigationItems" [routerLink]="item.path" routerLinkActive="active"
                (click)="closeMobileMenu()" class="mobile-nav-item">
                <app-icon [name]="item.icon" [size]="20"></app-icon>
                <span>{{ item.label }}</span>
            </a>
        </nav>
    </div>
</div>
<div class="header-spacer"></div>

// src/components/ui/Header.jsx
import React, { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import Icon from '../AppIcon';
import Button from './Button';

const Header = () => {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const location = useLocation();

  const navigationItems = [
<<<<<<< HEAD
    { label: 'Табло', path: '/dashboard-overview', icon: 'LayoutDashboard' },
=======
    { label: 'Dashboard', path: '/dashboard-overview', icon: 'LayoutDashboard' },
>>>>>>> 5bf2240c40b1ffe00401e90ffe8061c33962b09d
    { label: 'Регистрирани', path: '/cat-registry-list', icon: 'BookOpen' },
    { label: 'Карта', path: '/interactive-cat-map', icon: 'Map' },
  ];

  const isActivePath = (path) => {
    return location?.pathname === path;
  };

  const toggleMobileMenu = () => {
    setIsMobileMenuOpen(!isMobileMenuOpen);
  };

  const closeMobileMenu = () => {
    setIsMobileMenuOpen(false);
  };

  return (
    <>
      <header className="fixed top-0 left-0 right-0 z-[1000] bg-card shadow-warm transition-smooth">
        <div className="flex items-center justify-between h-16 px-4 lg:px-6">
          <div className="flex items-center gap-6">
            <Link 
              to="/dashboard-overview" 
              className="flex items-center gap-3 transition-smooth hover:opacity-80"
              onClick={closeMobileMenu}
            >
              <div className="flex items-center justify-center w-10 h-10 bg-primary/10 rounded-lg">
<<<<<<< HEAD
                <div className="flex items-center justify-center w-10 h-10 bg-primary/10 rounded-lg overflow-hidden">
                  <img
                    src="/logo.png"
                    alt="CastraMap logo"
                    className="w-full h-full object-contain"
                  />
                </div>
              </div>
              <span className="text-xl font-heading font-semibold text-foreground hidden sm:block">
                CastraMap
=======
                <Icon name="Cat" size={24} color="var(--color-primary)" />
              </div>
              <span className="text-xl font-heading font-semibold text-foreground hidden sm:block">
                Cat Vet Reg
>>>>>>> 5bf2240c40b1ffe00401e90ffe8061c33962b09d
              </span>
            </Link>

            <nav className="hidden lg:flex items-center gap-1">
              {navigationItems?.map((item) => (
                <Link
                  key={item?.path}
                  to={item?.path}
                  className={`
                    flex items-center gap-2 px-4 h-11 rounded-md font-medium transition-smooth
                    ${isActivePath(item?.path)
                      ? 'bg-primary text-primary-foreground'
                      : 'text-muted-foreground hover:bg-muted hover:text-foreground'
                    }
                  `}
                  aria-current={isActivePath(item?.path) ? 'page' : undefined}
                >
                  <Icon name={item?.icon} size={18} />
                  <span>{item?.label}</span>
                </Link>
              ))}
            </nav>
          </div>

          <div className="flex items-center gap-3">
            <Button
              variant="default"
              iconName="Plus"
              iconPosition="left"
              onClick={() => window.location.href = '#/cat-registration-form'}
              className="hidden sm:flex"
            >
              Нова котка
            </Button>

            <Button
              variant="default"
              size="icon"
              iconName="Plus"
              onClick={() => window.location.href = '#/cat-registration-form'}
              className="sm:hidden"
<<<<<<< HEAD
              aria-label="Регистрирай котка"
=======
              aria-label="Register Cat"
>>>>>>> 5bf2240c40b1ffe00401e90ffe8061c33962b09d
            />

            <button
              onClick={toggleMobileMenu}
              className="lg:hidden flex items-center justify-center w-11 h-11 rounded-md text-muted-foreground hover:bg-muted hover:text-foreground transition-smooth"
              aria-label="Toggle menu"
              aria-expanded={isMobileMenuOpen}
            >
              <Icon name={isMobileMenuOpen ? 'X' : 'Menu'} size={24} />
            </button>
          </div>
        </div>
      </header>

      {isMobileMenuOpen && (
        <div
          className="fixed inset-0 z-[1100] bg-background lg:hidden"
          onClick={closeMobileMenu}
        >
          <div className="pt-20 px-4">
            <nav className="flex flex-col gap-2">
              {navigationItems?.map((item) => (
                <Link
                  key={item?.path}
                  to={item?.path}
                  onClick={closeMobileMenu}
                  className={`
                    flex items-center gap-3 px-4 h-12 rounded-md font-medium transition-smooth
                    ${isActivePath(item?.path)
                      ? 'bg-primary text-primary-foreground'
                      : 'text-muted-foreground hover:bg-muted hover:text-foreground'
                    }
                  `}
                  aria-current={isActivePath(item?.path) ? 'page' : undefined}
                >
                  <Icon name={item?.icon} size={20} />
                  <span>{item?.label}</span>
                </Link>
              ))}
            </nav>
          </div>
        </div>
      )}
      <div className="h-16" />
    </>
  );
};

export default Header;
